# Generated by Django 3.2.7 on 2021-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.URLField(default='', max_length=1028),
        ),
    ]
