# Generated by Django 3.2.7 on 2021-12-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211209_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='amount_prize',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
