# Generated by Django 3.2.7 on 2021-12-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211104_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_prod',
        ),
    ]
