# Generated by Django 3.2.7 on 2021-12-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_cart_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_prod',
            field=models.CharField(default='', max_length=2047),
        ),
    ]
